name: Ollama Model Download and Package

on:
  workflow_dispatch:
    inputs:
      model_name:
        description: 'Model name to download, e.g., qwen3:0.6b'
        required: true

jobs:
  download-and-package-model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Ollama
      run: |
       curl https://ollama.ai/install.sh | bash

    - name: Pull the specified model
      env:
        MODEL_NAME: ${{ github.event.inputs.model_name }}
      run: |
        ollama pull ${MODEL_NAME}

    - name: Package the model
      env:
        MODEL_PATH: /usr/share/ollama/.ollama/models/${{ github.event.inputs.model_name }}
      run: |
        tar -czvf model.tar.gz -C $(dirname ${MODEL_PATH}) $(basename ${MODEL_PATH})

    - name: Upload the package as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: model-archive
        path: ./model.tar.gz



