name: Ollama Model Download and Package

on:
  workflow_dispatch:
    inputs:
      model_name:
        description: 'Name of the Ollama model to download'
        required: true
        type: string

jobs:
  download-and-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ollama
        run: |
          wget https://ollama.com/install.sh
          chmod +x install.sh
          sudo ./install.sh

      - name: Download Ollama model
        run: ollama pull ${{ github.event.inputs.model_name }}

      - name: Set safe model name
        id: set-safe-model-name
        run: |
          safe_model_name=$(echo "${{ github.event.inputs.model_name }}" | tr ':' '_')
          echo "safe_model_name=$safe_model_name" >> $GITHUB_OUTPUT

      - name: Package the model
        run: |
          model_dir="$HOME/.ollama/models/${{ github.event.inputs.model_name }}"
          if [ -d "$model_dir" ]; then
            mkdir -p models
            cp -r "$model_dir" models/
            tar -czvf "${{ steps.set-safe-model-name.outputs.safe_model_name }}.tar.gz" models
          else
            echo "Model directory $model_dir not found."
            exit 1
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.set-safe-model-name.outputs.safe_model_name }}-model
          path: ${{ steps.set-safe-model-name.outputs.safe_model_name }}.tar.gz    
