name: Ollama Model Download and Package

on:
  workflow_dispatch:
    inputs:
      model_name:
        description: 'Model name to download, e.g., qwen3:0.6b'
        required: true

jobs:
  download-and-package-model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Ollama
      run: |
        curl https://ollama.ai/install.sh | bash

    - name: Pull the specified model
      env:
        MODEL_NAME: ${{ github.event.inputs.model_name }}
      run: |
        ollama pull ${MODEL_NAME}

    - name: Check current path and package the models directory
      run: |
        echo "Current working directory: $(pwd)"
        ls -la /usr/share/ollama/.ollama/models/
        tar -czvf models.tar.gz /usr/share/ollama/.ollama/models/

    - name: Check if models.tar.gz exists
      run: |
        if [ ! -f ./models.tar.gz ]; then
          echo "Error: models.tar.gz not found!"
          exit 1
        fi

    - name: Upload the package as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: model-archive
        path: ./models.tar.gz
        if-no-files-found: warn
        compression-level: 6
        overwrite: false
        include-hidden-files: false



