name: Ollama Model Download and Package

on:
  workflow_dispatch:
    inputs:
      model_name:
        description: 'Name of the Ollama model to download'
        required: true
        type: string

jobs:
  download-and-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ollama
        run: |
          wget https://ollama.com/install.sh
          chmod +x install.sh
          sudo ./install.sh

      - name: Download Ollama model
        run: ollama pull ${{ github.event.inputs.model_name }}

      - name: Debug - List all Ollama models
        run: ollama list

      - name: Debug - List default Ollama models directory
        run: |
          default_model_dir="$HOME/.ollama/models"
          if [ -d "$default_model_dir" ]; then
            echo "Contents of $default_model_dir:"
            ls -l "$default_model_dir"
          else
            echo "Default Ollama models directory $default_model_dir not found."
          fi

      - name: Check if model is downloaded
        run: |
          if ! ollama list | grep -q "${{ github.event.inputs.model_name }}"; then
            echo "Model ${{ github.event.inputs.model_name }} not downloaded."
            exit 1
          fi

      - name: Set safe model name
        id: set-safe-model-name
        run: |
          safe_model_name=$(echo "${{ github.event.inputs.model_name }}" | tr ':' '_')
          echo "safe_model_name=$safe_model_name" >> $GITHUB_OUTPUT

      - name: Find model directory
        id: find-model-dir
        run: |
          # Use wildcard for fuzzy matching
          model_dir=$(find $HOME -type d -name "*$(echo ${{ github.event.inputs.model_name }} | tr -d ':')*" 2>/dev/null | head -n 1)
          if [ -z "$model_dir" ]; then
            echo "Model directory not found."
            exit 1
          fi
          echo "model_dir=$model_dir" >> $GITHUB_OUTPUT

      - name: Package the model
        run: |
          mkdir -p models
          cp -r ${{ steps.find-model-dir.outputs.model_dir }} models/
          tar -czvf "${{ steps.set-safe-model-name.outputs.safe_model_name }}.tar.gz" models

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.set-safe-model-name.outputs.safe_model_name }}-model
          path: ${{ steps.set-safe-model-name.outputs.safe_model_name }}.tar.gz    
