name: Download and Zip File

on:
  workflow_dispatch:
    inputs:
      fileUrl:
        description: 'URL of the file to download'
        required: true

jobs:
  download-and-zip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download file using curl
      id: download-file
      env:
        FILE_URL: ${{ github.event.inputs.fileUrl }}
      run: |
        curl -L "$FILE_URL" -o downloaded_file

    - name: Check if the downloaded file is a zip
      id: check_zip
      run: |
        if [[ $(file --mime-type -b downloaded_file) == "application/zip" ]]; then
          echo "::set-output name=is_zip::true"
        else
          echo "::set-output name=is_zip::false"
        fi

    - name: Unzip the file if it's a zip
      if: steps.check_zip.outputs.is_zip == 'true'
      run: unzip downloaded_file -d extracted_files

    - name: Create directory for non-zip files
      if: steps.check_zip.outputs.is_zip == 'false'
      run: mkdir -p extracted_files && mv downloaded_file extracted_files/

    - name: Zip the contents
      run: zip -r downloaded_file.zip extracted_files/

    - name: Upload ZIP as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: downloaded_file.zip
        path: downloaded_file.zip



