name: Node.js and Yarn Setup

on:
  workflow_dispatch:
    inputs:
      node-version:
        description: 'Node.js version'
        required: true
        default: '16.x'
      yarn-version:
        description: 'Yarn version'
        required: true
        default: 'latest'
      packages:
        description: 'Packages to install (comma-separated)'
        required: true
        default: 'eslint@8.0.0,prettier@2.0.0'

jobs:
  setup-and-install:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ github.event.inputs.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ github.event.inputs.node-version }}

      - name: Install Yarn ${{ github.event.inputs.yarn-version }}
        run: |
          npm install --global yarn@$GITHUB_EVENT_INPUT_YARN_VERSION

      - name: Install packages globally
        run: |
          IFS=',' read -ra ADDR <<< "${{ github.event.inputs.packages }}"
          for pkg in "${ADDR[@]}"; do
            echo "Installing package: $pkg"
            yarn global add "$pkg"
          done

      - name: Get Yarn Cache Directory
        id: get-cache-dir
        run: |
          echo "::set-output name=CACHE_DIR::$(yarn cache dir)"

      - name: Archive cache directory
        uses: actions/upload-artifact@v4
        with:
          name: yarn-cache-${{ github.run_id }}
          path: ${{ steps.get-cache-dir.outputs.CACHE_DIR }}



